name: Deploy plain HTML to GitHub Pages

on:
  push:
    branches: [main]  # or 'master' if that's your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # assuming your HTML files are in the root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
